# Generated by Django 2.2.4 on 2022-11-26 11:38

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20221110_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=254)),
                ('screenshot', models.URLField(verbose_name='screenshot url')),
                ('next_cancel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.SubCancellation')),
                ('subscribe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Subscribe')),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=32, null=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='SubTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(blank=True, max_length=32, null=True)),
                ('purchase_price', models.BigIntegerField(default=0)),
                ('sub_cancel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.SubCancellation')),
            ],
        ),
        migrations.AddField(
            model_name='subscribe',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.SubGroup'),
        ),
    ]
