# Generated by Django 2.2.4 on 2022-12-04 16:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20221126_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
