# Generated by Django 2.2.4 on 2022-12-04 16:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20221204_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
